# Generated by Django 2.0.1 on 2018-01-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hellow_world_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rocks',
            new_name='Rock',
        ),
    ]
